name = "PlantShapes"
uuid = "5ea97238-1e7b-4d52-b7cd-c1b3d9e8d8c9"
authors = ["anaIFernst <ana.ferreiraernst@wur.nl> and contributors"]
version = "1.0.0-DEV"

[deps]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
julia = "1.6.7"
Aqua = "0.5"
Unitful = "1.0"
Test = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
